name: ppde-test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - mamba
  - pip
  - poetry=1.*
  - torchvision
  - cudatoolkit
  - pytorch::pytorch=1.13.0
  - biopython=1.81
  - pandas=1.4.2
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - matplotlib
  - tqdm=4.64.1
  - cma=3.3.0
  - pip:
    - git+https://github.com/pemami4911/esm_one_hot.git